# dem4cli version 2 demo

## Description 


## Functions

**Part 1. Demographics preprocesing**

- load_cohort_sizes() loads cohort sizes from Wittgenstein SSP IIASA reconstructions and projections
    - v1 is from WCDEv2, v2 is from WCDE v3.2-beta
- interpolate_cohortsize_countries() interpolates from 5-year age brackets to exact ages
- load_population() loads gridded pop data
    - v1 from ISIMIP3, v2 from COMPASS (pre-CMIP7 version)
- load_unwpp_lifeexpectancy() loads and cleans life expectancy data e(x) at age 5 from UNWPP2024
- get_life_expectancies() goes from raw e(x) data to period -> cohort life expectancy at birth 
- load_countrymasks_fillcoasts() loads fractional countrymasks, with options for filling coastal pixels to sum to 1 

**Part 2. Lifetime exposure**
- GMT mapping 
- lifetime exposure computation


## Notes
- load_country_metadata() only v1 
- load_country_stats() only v1 and not very useful
- get_gridscale_demographics() and population_demographics_gridscale_global() only v1
- 197 countries included in all data sources and with SSP cohort size projections (218 included in all 3 but without cohort size projs)
    - Could get cohort sizes from UNWPP2024! Might lose less countries


## To Do
- wrapper fxn in same(ish) format as S2S

In [1]:
import numpy as np
import xarray as xr
import pandas as pd
import geopandas as gpd
import pickle as pk
from scipy import interpolate
#import regionmask
import glob, os, re, sys
import openpyxl
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_rows', 80)
%matplotlib inline 

sys.path.append('..')
from population_demographics_v2 import *

In [2]:
flags

# in init function user can define these

{'version': 2, 'pop_resolution': 0.1, 'GMT_mapping': 'year_to_year'}

In [3]:
bbox_europe = [ 31.99,  71.09, -14.96,  34.94]

## Part 1. Demographics preprocessing

In [3]:
df_cohort_sizes, ages, years = load_cohort_sizes(dir_cohortsizes, ssp=2, by_sex=False)

# loads raw cohort size data from historical + ssp and cleans to keep only relevant information

# TODO: note that could get this from UNWPP2024!

In [4]:
da_cohort_size = interpolate_cohortsize_countries(
                        df_cohort_sizes,
                        ages,
                        years,
                    )

# interpolates cohort sizes from 5 year to single year and corrects to preserve mean

# TODO: with this new data the neg numbers happens more, check if this is big or small issue

interpolating cohort sizes per country
after interpolation and mean-preserving correction there are some neg numbers in 6, Anguilla, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 15, Bahrain, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 29, British Virgin Islands, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 32, Burkina Faso, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 39, Central African Republic, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 61, El Salvador, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 65, Eswatini, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 68, Faroe Islands, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 69, Fiji, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 74, Gabon, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 106, Jordan, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 125, Malaysia, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 127, Mali, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 128, Malta, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 138, Mongolia, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 151, Niger, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 158, Oman, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 183, San Marino, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 191, Sint Maarten (Dutch part), setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 198, South Sudan, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 210, Timor-Leste, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 231, Wallis and Futuna, setting them to zero

In [ ]:
df_unwpp = load_unwpp_lifeexpectancy(filepath_lifeexpectancy = filepath_lifeexpectancy) # load life expectancy data and clean 
df_life_expectancy_5 = get_life_expectancies(df_unwpp,
                                            #extend=True,
                                            start_birthyear=1950,
                                            end_birthyear=2025) # go from 'period' to 'cohort' life expectancy

In [ ]:
da_population = load_population(
    dir_population= dir_population, 
    startyear=1950,
    endyear=2100,
    ssp=2,
    urbanrural=False,
    bbox = [ 31.99,  71.09, -14.96,  34.94] # optional : latmin, latmax, lonmin, lonmax

)

# load gridded population data, crop over Europe (optional cropping)

opening compass - historical
opening compass - ssp2

In [4]:
# open country masks

da_countrymasks = load_countrymasks_fillcoasts(
                            filepath_countrymask,
                            preprocess=False, # True if you want to preprocess
                            fillcoast=False, # fill coastal pixels to not lose coastal pops (done in preprocessed files)
                            fix_smallislands=False, # done in preprocessed input files for 0.5, not for 0.1 - TODO: check if necessary at 0.1 or not ! 
                            bbox=bbox_europe,
                            )

# these are already preprocessed (cleaned country names and coastal pixels are filled to sum to 1 to not lose population)

In [8]:
# lookup table

# fxn that matches the names in cohort size and this and mask / lookup table for v2 


#TODO just add column from cohort size name to Dominik's lookup table matching based on ISO number and save 

df_lookuptable = pd.read_csv(filepath_lookuptable) # new

In [4]:
# wrapper function that runs everything for S2S / lifetime exposure calcs


d_countries = preprocess_all_country_data(

    dir_cohortsizes = dir_cohortsizes,  # cohort size data
    ssp=2, 
    by_sex=False,                       # NOTE by_sex not implemented
                                            
    filepath_lifeexpectancy = filepath_lifeexpectancy, # life expectancy data
    start_birthyear=1950,
    end_birthyear=2025, 

    dir_population= dir_population,     # gridded pop data 
    startyear=1950,
    endyear=2100,
    urbanrural=False,                   # NOTE urbanrural not implemented for v2
    bbox = bbox_europe,

    filepath_countrymask = filepath_countrymask ,   # country masks 
    preprocess=False,                               # NOTE preprocessing is already done in standard input files 
    fillcoast=False, 
    fix_smallislands=False,
)




#TODO filter countries to have only the ones included in all the

interpolating cohort sizes per country
after interpolation and mean-preserving correction there are some neg numbers in 6, Anguilla, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 15, Bahrain, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 29, British Virgin Islands, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 32, Burkina Faso, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 39, Central African Republic, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 61, El Salvador, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 65, Eswatini, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 68, Faroe Islands, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 69, Fiji, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 74, Gabon, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 106, Jordan, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 125, Malaysia, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 127, Mali, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 128, Malta, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 138, Mongolia, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 151, Niger, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 158, Oman, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 183, San Marino, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 191, Sint Maarten (Dutch part), setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 198, South Sudan, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 210, Timor-Leste, setting them to zero
after interpolation and mean-preserving correction there are some neg numbers in 231, Wallis and Futuna, setting them to zero
opening compass - historical
opening compass - ssp2

In [5]:
d_countries

{'info_pop': None,
 'borders': <xarray.DataArray (lat: 391, lon: 499, country: 49)>
 dask.array<getitem, shape=(391, 499, 49), dtype=float32, chunksize=(337, 430, 18), chunktype=numpy.ndarray>
 Coordinates:
   * lon      (lon) float64 -14.95 -14.85 -14.75 -14.65 ... 34.65 34.75 34.85
   * lat      (lat) float64 32.05 32.15 32.25 32.35 ... 70.75 70.85 70.95 71.05
   * country  (country) object 'ALB' 'AND' 'AUT' 'BEL' ... 'TUN' 'TUR' 'UKR',
 'population_map': <xarray.DataArray 'total-population' (time: 151, lat: 391, lon: 499)>
 dask.array<concatenate, shape=(151, 391, 499), dtype=float32, chunksize=(1, 180, 349), chunktype=numpy.ndarray>
 Coordinates:
   * lon      (lon) float64 -14.95 -14.85 -14.75 -14.65 ... 34.65 34.75 34.85
   * lat      (lat) float64 32.05 32.15 32.25 32.35 ... 70.75 70.85 70.95 71.05
   * time     (time) int64 1950 1951 1952 1953 1954 ... 2096 2097 2098 2099 2100
 Attributes:
     units:      1
     long_name:  Population_count,
 'birth_years': None,
 'life_expectancy_5': Country  Afghanistan  Albania  Algeria  American Samoa  Andorra   Angola  \
 Year
 1950         54.7051  72.2933  60.0833         73.0935  78.4736  60.3326
 1951         54.9914  73.1170  59.9968         73.3142  78.7848  60.4601
 1952         55.3287  74.0791  59.8907         73.5873  79.0685  60.5222
 1953         55.6465  75.0774  59.7686         74.0095  79.4490  60.5925
 1954         55.9651  75.9208  59.6571         74.5568  79.7661  60.6646
 1955         56.2518  76.5891  59.5298         75.0851  80.1218  60.7478
 1956         56.5746  76.9806  59.4297         75.4831  80.4959  58.9827
 1957         56.8662  77.3068  58.1319         75.6528  80.8279  59.0979
 1958         57.1442  77.6003  62.5451         75.6224  81.0699  59.1849
 1959         57.4391  77.8344  62.3755         75.4186  81.3260  59.3060
 1960         57.7189  78.0204  62.2297         75.1105  81.5076  59.3914
 1961         58.0074  78.2347  62.1170         69.3936  81.6309  59.5049
 1962         58.2920  78.4212  62.0671         74.6203  81.7016  59.7026
 1963         58.5808  78.6150  62.0842         74.5299  81.7717  59.8912
 1964         58.8706  78.7762  62.1833         74.6192  81.8219  60.0902
 1965         59.1687  78.9203  62.3926         74.8310  81.9382  60.2884
 1966         59.4562  79.0666  62.6814         75.1436  82.0627  60.5218
 1967         59.7657  79.2167  63.0726         75.4686  82.2618  60.7655
 1968         60.0959  79.3639  63.5357         75.7972  82.4508  61.0275
 1969         60.4167  79.5032  64.0905         76.0489  82.6505  61.2753
 1970         60.7320  79.6464  64.7213         76.2570  82.8388  60.6559
 1971         61.0439  79.7978  65.4510         76.3753  83.0965  60.5042
 1972         61.3822  79.9665  66.2214         76.5024  83.3399  60.7955
 1973         60.0824  80.1270  67.0676         76.5848  83.6280  61.0357
 1974         58.5670  80.1989  68.3057         76.7249  83.9141  61.2637
 1975         58.7554  80.3305  69.8300         76.9371  84.1908  61.4860
 1976         58.6674  80.4414  72.0340         77.1761  84.4119  61.7011
 1977         55.0640  80.6061  73.3599         77.3498  84.6092  61.9091
 1978         55.3121  80.7740  74.1081         77.4755  84.7583  60.9350
 1979         50.0776  80.9350  74.7404         77.5871  84.8713  61.1331
 1980         50.5612  81.1171  75.4745         77.7533  84.9494  61.3194
 1981         56.5389  81.3592  76.0237         77.8945  85.0363  61.4998
 1982         56.7371  81.5326  76.4537         77.9958  85.1072  59.5114
 1983         60.7699  81.6171  76.9386         78.0326  85.2629  60.1715
 1984         61.7370  81.7096  77.2892         78.0657  85.4352  60.3659
 1985         62.0836  81.8232  77.3472         78.2353  85.8022  60.4987
 1986         62.2276  81.9880  77.2852         78.4325  86.1526  62.4238
 1987         62.7879  82.1766  77.2532         78.6240  86.5596  60.9838
 1988         66.9148  82.3991  77.2748         78.6439  86.9168  60.2548
 1989         66.3670  82.4982  76.6837         78.6632  87.2884  61.5755
 1990         67.4008  82.5789  77.0440         78.6489  87.4940  64.7650
 1991         67.8862  82.5682  77.5230         78.6481  87.6851  64.9575
 1992         68.1233  81.8671  78.1107         78.6653  87.8113  65.0943
 1993         67.1524  82.6107  78.5063         78.5856  87.9391  63.6988
 1994         68.9897  82.7233  79.2029         78.5106  88.1927  63.5741
 1995         69.2145  82.8799  79.6099         78.4503  88.4875  64.3074
 1996         69.5061  83.0341  80.0122         78.5608  88.7695  64.3596
 1997         70.0493  83.1472  80.4907         78.7192  89.0421  65.1003
 1998         70.6820  83.2965  80.6795         78.7940  89.2989  67.0190
 1999         71.0834  83.5871  81.1726         79.1907  89.3928  67.5175
 2000         71.2942  83.9607  81.3690         79.2683  89.6477  68.0929
 2001         71.3432  84.4256  81.5512         79.2585  89.9195  68.5001
 2002         71.4457  85.0258  81.6947         79.2039  90.1611  69.2406
 2003         71.9737  85.4890  81.8845         79.2536  90.3699  69.8399
 2004         72.3794  85.6568  82.0621         78.0053  90.6014  70.3003
 2005         72.6363  85.4733  82.2709         79.3943  90.6948  70.8782
 2006         72.9557  85.2839  82.4600         79.4671  90.7930  71.3057
 2007         73.2393  84.9973  82.6438         79.5133  90.8288  71.7176
 2008         73.5071  84.8549  82.8058         79.5737  90.8997  72.1411
 2009         73.4712  84.8480  82.9564         79.4913  90.9760  72.5152
 2010         73.3616  85.1499  83.0930         79.4584  91.0214  72.8933
 2011         73.5795  85.4168  83.2131         79.4436  90.9820  73.2221
 2012         72.8820  85.6616  83.3026         79.6051  90.8597  73.4964
 2013         72.7560  85.9935  83.3919         79.5953  90.7478  73.8035
 2014         73.1937  86.2291  83.4807         79.5478  90.6112  74.0538
 2015         71.5263  84.5616  80.9568         79.4620  85.9325  73.9216
 2016         70.3183  83.5718  82.9103         79.4927  88.8391  73.5724
 2017         75.6159  85.5569  83.8087         79.5302  90.5326  74.7739
 2018         75.9220  86.3595  83.9010         79.6241  90.5553  75.0080
 2019         75.9220  86.3595  83.9010         79.6241  90.5553  75.0080
 2020         75.9220  86.3595  83.9010         79.6241  90.5553  75.0080
 2021         75.9220  86.3595  83.9010         79.6241  90.5553  75.0080
 2022         75.9220  86.3595  83.9010         79.6241  90.5553  75.0080
 2023         75.9220  86.3595  83.9010         79.6241  90.5553  75.0080
 2024         75.9220  86.3595  83.9010         79.6241  90.5553  75.0080
 2025         75.9220  86.3595  83.9010         79.6241  90.5553  75.0080

 Country  Anguilla  Antigua and Barbuda  Argentina  Armenia  ...  Uruguay  \
 Year                                                        ...
 1950      71.0196              72.9259    73.9860  73.5868  ...  76.9994
 1951      71.3453              73.1271    74.8442  73.7835  ...  77.1543
 1952      71.6498              73.3441    74.3825  73.9763  ...  77.3030
 1953      71.9511              73.5912    75.4063  74.1662  ...  77.4524
 1954      72.3025              73.8626    75.2090  74.3545  ...  77.5948
 1955      71.4231              74.0973    75.3088  74.5424  ...  77.7112
 1956      72.9037              74.4576    75.6636  74.7311  ...  77.8104
 1957      73.1615              74.7743    75.5765  74.9164  ...  77.8888
 1958      73.4077              75.1173    75.7557  75.0945  ...  77.9640
 1959      73.6521              75.4859    75.6297  75.2621  ...  78.0164
 1960      73.9123              75.8740    75.7983  75.4159  ...  78.0689
 1961      74.1484              76.2682    76.0868  75.5530  ...  78.1345
 1962      74.3112              76.6421    76.0765  75.6725  ...  78.2081
 1963      74.4871              77.0067    75.7326  75.7746  ...  78.2765
 1964      74.6502              77.3599    75.4729  75.8593  ...  78.3278
 1965      74.9072              77.6921    75.9621  75.9267  ...  78.4277
 1966      75.1535              78.0012    75.8044  75.9768  ...  78.5528
 1967      75.3585              78.2898    76.0218  76.0154  ...  78.6909
 1968      75.5302              78.5616    76.1302  76.0444  ...  78.7876
 1969      75.7228              78.8288    76.2122  76.0688  ...  78.8851
 1970      75.9635              79.0734    76.6430  76.0936  ...  78.9872
 1971      76.1762              79.3198    76.5617  76.1240  ...  79.0914
 1972      76.3971              79.5791    77.0079  76.1912  ...  79.2068
 1973      76.6458              79.8407    77.2646  76.2778  ...  79.3597
 1974      76.8808              80.0816    77.5500  76.3895  ...  79.2941
 1975      77.0727              80.2768    77.5451  76.5026  ...  79.4659
 1976      77.2954              80.4384    77.6804  76.6507  ...  79.6935
 1977      77.5144              80.5892    77.6703  76.8350  ...  80.0583
 1978      77.7533              80.7071    77.8825  77.0356  ...  80.0227
 1979      77.9445              80.8010    77.8474  77.2258  ...  80.1336
 1980      78.1493              80.8467    78.3088  77.3815  ...  80.2871
 1981      78.4093              80.8575    78.6494  77.4796  ...  80.4570
 1982      78.6612              80.8378    79.0147  77.4963  ...  80.2669
 1983      78.9186              80.7824    79.3671  64.5350  ...  80.2820
 1984      79.2324              80.6396    79.7263  77.3252  ...  80.4104
 1985      79.4776              80.6070    79.7945  77.1820  ...  80.7385
 1986      79.7752              80.4983    80.1557  77.0978  ...  80.8893
 1987      80.0458              80.4377    80.1739  77.0433  ...  80.8691
 1988      80.3292              80.4664    80.3254  77.1656  ...  80.8059
 1989      80.5981              80.5932    80.7012  77.3427  ...  80.8206
 1990      80.8507              80.7196    80.7714  77.5846  ...  81.1045
 1991      81.1074              80.9712    80.9017  77.8519  ...  81.3619
 1992      81.3586              81.1831    81.1954  78.1373  ...  81.4242
 1993      81.5879              81.3461    81.1338  78.4416  ...  81.4235
 1994      81.8319              81.6063    81.3477  78.7500  ...  81.6092
 1995      82.0531              81.9329    81.5187  79.0430  ...  81.9380
 1996      82.2723              82.2053    81.7084  79.3064  ...  82.2062
 1997      82.5032              82.3127    81.8119  79.5222  ...  82.2575
 1998      82.7137              82.3649    81.7533  79.6762  ...  82.3436
 1999      82.9280              82.3575    82.2755  79.7766  ...  82.5426
 2000      83.1040              82.3683    82.5900  79.8435  ...  82.8790
 2001      83.3133              82.4894    82.5961  79.8952  ...  82.8830
 2002      83.4743              82.6846    82.0481  79.9541  ...  83.0895
 2003      83.6035              83.0241    82.6615  80.0380  ...  83.1765
 2004      83.7248              83.3187    82.7737  80.1600  ...  83.4698
 2005      83.8704              83.6197    82.8382  80.3164  ...  83.4563
 2006      83.9493              83.9275    83.2240  80.4991  ...  83.3980
 2007      84.0314              83.9890    82.8916  80.6941  ...  83.5125
 2008      84.2325              83.9225    82.8841  80.9087  ...  83.7379
 2009      84.2874              83.7689    83.2929  81.1205  ...  83.9289
 2010      84.3147              83.7350    83.5940  81.3196  ...  83.9854
 2011      84.4332              83.7978    83.0647  81.5330  ...  84.0119
 2012      83.9649              83.8558    83.4824  81.7355  ...  84.1982
 2013      84.7606              83.9345    83.6844  81.9246  ...  84.1429
 2014      84.9342              83.9545    83.7378  82.0962  ...  84.1236
 2015      85.1499              83.9408    82.7324  75.6764  ...  84.9071
 2016      84.8946              83.9490    80.7574  79.3409  ...  81.9701
 2017      85.5844              84.2200    82.6124  81.4055  ...  83.0513
 2018      85.7620              84.3227    84.1949  82.4296  ...  84.6663
 2019      85.7620              84.3227    84.1949  82.4296  ...  84.6663
 2020      85.7620              84.3227    84.1949  82.4296  ...  84.6663
 2021      85.7620              84.3227    84.1949  82.4296  ...  84.6663
 2022      85.7620              84.3227    84.1949  82.4296  ...  84.6663
 2023      85.7620              84.3227    84.1949  82.4296  ...  84.6663
 2024      85.7620              84.3227    84.1949  82.4296  ...  84.6663
 2025      85.7620              84.3227    84.1949  82.4296  ...  84.6663

 Country  Uzbekistan  Vanuatu  Venezuela (Bolivarian Republic of)  Viet Nam  \
 Year
 1950        71.5994  62.5983                             68.7405   68.7827
 1951        71.7428  63.0074                             69.2576   69.2194
 1952        71.8910  63.3789                             69.7610   69.5801
 1953        72.0515  63.7587                             70.2772   69.9530
 1954        72.2161  64.1316                             70.8107   70.2969
 1955        72.3857  64.4970                             71.2998   70.7099
 1956        72.5400  64.8439                             71.8403   70.9153
 1957        72.7043  65.1820                             72.1860   70.5560
 1958        72.8695  65.5151                             72.8415   69.2959
 1959        73.0483  65.7670                             73.3200   69.7773
 1960        73.2214  66.0903                             73.8741   69.2197
 1961        73.3959  66.4161                             74.6839   69.1335
 1962        73.5756  66.7549                             75.1533   68.9568
 1963        73.7589  67.0820                             75.2634   65.3828
 1964        73.9453  67.3783                             74.9328   67.2308
 1965        74.1337  67.6945                             75.7311   67.3449
 1966        74.3166  68.0355                             75.8658   67.9047
 1967        74.4947  68.3298                             76.0127   64.6811
 1968        74.6553  68.7249                             75.9723   67.9440
 1969        74.8126  69.0915                             76.2654   67.1176
 1970        74.9559  69.4511                             76.5534   73.2667
 1971        75.0985  69.7826                             76.9767   74.8098
 1972        75.2416  70.1645                             77.2896   75.1313
 1973        75.3793  70.5946                             77.5280   75.5139
 1974        75.5123  71.4276                             77.5002   75.8905
 1975        75.6453  71.6259                             77.3175   76.1586
 1976        75.7338  72.0310                             77.7318   76.5119
 1977        75.8061  72.4007                             77.9048   76.8631
 1978        75.9079  72.7175                             78.3644   77.1163
 1979        76.0725  72.9488                             78.3902   77.4040
 1980        76.3463  73.2086                             78.5832   77.5702
 1981        76.6064  73.6805                             79.0609   77.8150
 1982        76.8907  73.5682                             79.1149   78.1470
 1983        77.0034  74.4727                             79.1141   78.6012
 1984        76.9599  74.7176                             79.0688   78.6735
 1985        76.7808  75.2345                             79.1524   78.7181
 1986        76.4630  75.5763                             79.2893   78.8288
 1987        76.1049  75.8265                             79.2330   78.9690
 1988        75.7355  76.0593                             79.3870   79.1358
 1989        75.4393  76.2433                             79.2227   79.3983
 1990        75.3790  76.3104                             79.6013   79.7360
 1991        75.4309  76.3364                             79.7525   80.0256
 1992        75.6075  76.4318                             80.3503   80.2912
 1993        75.6432  76.4607                             80.1683   80.7484
 1994        75.6481  76.1328                             79.7988   80.9370
 1995        75.6399  76.6169                             79.9913   81.0003
 1996        75.8674  76.7361                             78.5381   81.1479
 1997        76.2091  76.8180                             80.3301   81.2149
 1998        76.4840  76.8914                             79.4991   81.2363
 1999        76.6161  76.9232                             80.1697   81.0009
 2000        76.6667  77.0697                             80.4641   81.0868
 2001        76.8706  76.9919                             80.3201   81.1441
 2002        77.2380  76.9667                             80.6772   81.2002
 2003        77.5842  77.0802                             79.8748   81.2402
 2004        77.8693  77.1524                             80.0755   81.2816
 2005        77.9986  77.2523                             80.3875   81.3454
 2006        78.1307  77.3648                             80.3882   81.4274
 2007        78.2392  77.4932                             80.3934   81.4583
 2008        78.3788  77.5436                             80.3967   81.5046
 2009        78.5340  77.6044                             80.1684   81.5504
 2010        78.7825  77.6935                             80.3531   81.6055
 2011        78.9365  77.8728                             79.3452   81.6203
 2012        79.0092  77.9498                             79.2700   81.6486
 2013        79.1989  78.0505                             80.0310   81.7073
 2014        79.2278  78.1810                             80.1476   81.7986
 2015        78.5398  77.7492                             79.7444   82.9812
 2016        78.7135  77.2663                             78.8997   81.6958
 2017        79.1283  78.6081                             79.9506   82.0417
 2018        79.3779  78.7511                             79.8957   82.1112
 2019        79.3779  78.7511                             79.8957   82.1112
 2020        79.3779  78.7511                             79.8957   82.1112
 2021        79.3779  78.7511                             79.8957   82.1112
 2022        79.3779  78.7511                             79.8957   82.1112
 2023        79.3779  78.7511                             79.8957   82.1112
 2024        79.3779  78.7511                             79.8957   82.1112
 2025        79.3779  78.7511                             79.8957   82.1112

 Country  Wallis and Futuna Islands  Western Sahara    Yemen   Zambia  Zimbabwe
 Year
 1950                       60.0066         58.8167  63.0338  68.3711   67.5054
 1951                       60.2678         59.0545  63.2106  68.5591   67.7423
 1952                       60.5338         59.2911  63.3482  68.7140   67.9825
 1953                       60.8083         59.5263  63.5801  68.9539   68.2102
 1954                       61.0874         59.7591  63.7344  69.1736   68.4717
 1955                       61.3774         59.9861  63.9845  69.3474   68.7514
 1956                       61.6823         60.2073  64.2225  69.5762   69.0324
 1957                       62.0178         60.4371  63.0699  69.7255   69.3188
 1958                       62.3610         60.6635  62.1884  69.8720   69.6035
 1959                       62.7058         60.8862  63.5036  69.2804   69.8868
 1960                       63.0560         61.1062  63.7251  70.1158   70.1644
 1961                       63.3635         61.3268  63.8394  70.2208   70.4254
 1962                       63.7366         61.5673  64.1511  70.3304   70.6642
 1963                       64.1477         61.8153  64.5600  70.3938   70.8911
 1964                       64.5807         62.0784  65.7521  70.5657   71.1126
 1965                       65.0163         62.3599  66.1260  70.7371   71.2992
 1966                       65.4493         62.3854  66.8198  71.0043   71.4667
 1967                       65.8949         62.7630  67.1185  71.2742   71.6010
 1968                       66.3628         63.1904  67.3875  71.5907   71.4622

### Check data

In [ ]:
da_cohort_size # from ssps 

# NOTE! overlap between mask, UNWPP and SSP projections is 218 countries 

# NOTE! of these only 197 countries have full cohort size projections into future!

# TODO could check if with UNWPP cohort size projections this is better - but then would be inconsistent with gridded pop national totals (that come from SSPs) - decide how to deal with this

<xarray.DataArray 'cohort_size' (country: 236, time: 151, ages: 105)>
array([[[2.73567360e-01, 2.61743480e-01, 2.49919600e-01, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [2.73309184e-01, 2.62139952e-01, 2.50970720e-01, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [2.73051008e-01, 2.62536424e-01, 2.52021840e-01, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        ...,
        [1.19588425e+00, 1.20333086e+00, 1.21077748e+00, ...,
         2.38331824e-04, 0.00000000e+00, 0.00000000e+00],
        [1.18756014e+00, 1.19529399e+00, 1.20302784e+00, ...,
         2.56643380e-04, 0.00000000e+00, 0.00000000e+00],
        [1.17923604e+00, 1.18725712e+00, 1.19527820e+00, ...,
         2.74954937e-04, 0.00000000e+00, 0.00000000e+00]],

       [[3.90316400e-02, 3.79113200e-02, 3.67910000e-02, ...,
         1.99376947e-06, 0.00000000e+00, 0.00000000e+00],
        [4.13674160e-02, 4.00184880e-02, 3.86695600e-02, ...,
         2.18182113e-06, 0.00000000e+00, 0.00000000e+00],
        [4.37031920e-02, 4.21256560e-02, 4.05481200e-02, ...,
         2.36987279e-06, 0.00000000e+00, 0.00000000e+00],
...
        [5.17906600e-01, 5.20906640e-01, 5.23906680e-01, ...,
         2.24356300e-04, 0.00000000e+00, 0.00000000e+00],
        [5.14445400e-01, 5.17453120e-01, 5.20460840e-01, ...,
         2.36712206e-04, 0.00000000e+00, 0.00000000e+00],
        [5.10984200e-01, 5.13999600e-01, 5.17015000e-01, ...,
         2.49068113e-04, 0.00000000e+00, 0.00000000e+00]],

       [[1.02697080e-01, 9.89636400e-02, 9.52302000e-02, ...,
         3.92156863e-07, 0.00000000e+00, 0.00000000e+00],
        [1.10939600e-01, 1.06367600e-01, 1.01795600e-01, ...,
         3.55979011e-07, 0.00000000e+00, 0.00000000e+00],
        [1.19182120e-01, 1.13771560e-01, 1.08361000e-01, ...,
         3.19801160e-07, 0.00000000e+00, 0.00000000e+00],
        ...,
        [2.54660296e-01, 2.56762928e-01, 2.58865560e-01, ...,
         4.76045919e-04, 0.00000000e+00, 0.00000000e+00],
        [2.52330008e-01, 2.54450744e-01, 2.56571480e-01, ...,
         5.10386444e-04, 0.00000000e+00, 0.00000000e+00],
        [2.49999720e-01, 2.52138560e-01, 2.54277400e-01, ...,
         5.44726970e-04, 0.00000000e+00, 0.00000000e+00]]])
Coordinates:
  * country  (country) object 'Afghanistan' 'Albania' ... 'Zambia' 'Zimbabwe'
  * time     (time) int64 1950 1951 1952 1953 1954 ... 2096 2097 2098 2099 2100
  * ages     (ages) int64 0 1 2 3 4 5 6 7 8 ... 96 97 98 99 100 101 102 103 104

In [8]:
da_population

<xarray.DataArray 'total-population' (time: 151, lat: 391, lon: 499)>
dask.array<concatenate, shape=(151, 391, 499), dtype=float32, chunksize=(1, 180, 349), chunktype=numpy.ndarray>
Coordinates:
  * lon      (lon) float64 -14.95 -14.85 -14.75 -14.65 ... 34.65 34.75 34.85
  * lat      (lat) float64 32.05 32.15 32.25 32.35 ... 70.75 70.85 70.95 71.05
  * time     (time) int64 1950 1951 1952 1953 1954 ... 2096 2097 2098 2099 2100
Attributes:
    units:      1
    long_name:  Population_count

In [ ]:
df_life_expectancy_5

# life expectancy at age 5 (corrected to be at birth and period) for each country/birth year - last data is for 2018 birth year, extra years are held constant

# TODO: country names from UNWPP life expectancy - to do fxn that matches the names in cohort size and this and mask / lookup table for v2

Country,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,...,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Wallis and Futuna Islands,Western Sahara,Yemen,Zambia,Zimbabwe
Year,,,,,,,,,,,,,,,,,,,,,
1945,53.3261,69.2296,63.5840,72.0589,76.7722,59.7620,69.7683,71.8547,73.1144,72.5277,...,76.2805,70.9224,60.4022,66.0496,62.9989,59.1348,57.6815,62.4295,67.3650,66.3182
1946,53.5996,69.4998,64.1647,72.1837,77.0034,59.8569,70.0189,72.1268,73.4322,72.7482,...,76.4038,71.0670,58.9680,66.7221,63.3894,59.2239,57.9052,62.5490,67.5156,66.5690
1947,53.8688,70.1581,64.1422,72.4278,77.2782,59.9553,70.2406,72.3293,74.1116,72.9654,...,76.5524,71.1997,61.3336,67.2419,63.7909,59.3332,58.1262,62.6602,67.7378,66.8106
1948,54.1415,70.9094,64.0927,72.6784,77.7080,60.0900,70.4861,72.5323,73.9636,73.1779,...,76.6936,71.3296,61.6748,67.7611,64.1265,59.5364,58.3487,62.8188,67.9695,67.0438
1949,54.1671,71.5560,59.9824,72.8803,78.1366,60.1895,70.7363,72.7200,74.4988,73.3851,...,76.8463,71.4600,62.1492,68.2673,66.4409,59.7734,58.5814,62.9305,68.1568,67.2780
1950,54.7051,72.2933,60.0833,73.0935,78.4736,60.3326,71.0196,72.9259,73.9860,73.5868,...,76.9994,71.5994,62.5983,68.7405,68.7827,60.0066,58.8167,63.0338,68.3711,67.5054
1951,54.9914,73.1170,59.9968,73.3142,78.7848,60.4601,71.3453,73.1271,74.8442,73.7835,...,77.1543,71.7428,63.0074,69.2576,69.2194,60.2678,59.0545,63.2106,68.5591,67.7423
1952,55.3287,74.0791,59.8907,73.5873,79.0685,60.5222,71.6498,73.3441,74.3825,73.9763,...,77.3030,71.8910,63.3789,69.7610,69.5801,60.5338,59.2911,63.3482,68.7140,67.9825
1953,55.6465,75.0774,59.7686,74.0095,79.4490,60.5925,71.9511,73.5912,75.4063,74.1662,...,77.4524,72.0515,63.7587,70.2772,69.9530,60.8083,59.5263,63.5801,68.9539,68.2102
1954,55.9651,75.9208,59.6571,74.5568,79.7661,60.6646,72.3025,73.8626,75.2090,74.3545,...,77.5948,72.2161,64.1316,70.8107,70.2969,61.0874,59.7591,63.7344,69.1736,68.4717
1955,56.2518,76.5891,59.5298,75.0851,80.1218,60.7478,71.4231,74.0973,75.3088,74.5424,...,77.7112,72.3857,64.4970,71.2998,70.7099,61.3774,59.9861,63.9845,69.3474,68.7514
1956,56.5746,76.9806,59.4297,75.4831,80.4959,58.9827,72.9037,74.4576,75.6636,74.7311,...,77.8104,72.5400,64.8439,71.8403,70.9153,61.6823,60.2073,64.2225,69.5762,69.0324
1957,56.8662,77.3068,58.1319,75.6528,80.8279,59.0979,73.1615,74.7743,75.5765,74.9164,...,77.8888,72.7043,65.1820,72.1860,70.5560,62.0178,60.4371,63.0699,69.7255,69.3188
1958,57.1442,77.6003,62.5451,75.6224,81.0699,59.1849,73.4077,75.1173,75.7557,75.0945,...,77.9640,72.8695,65.5151,72.8415,69.2959,62.3610,60.6635,62.1884,69.8720,69.6035
1959,57.4391,77.8344,62.3755,75.4186,81.3260,59.3060,73.6521,75.4859,75.6297,75.2621,...,78.0164,73.0483,65.7670,73.3200,69.7773,62.7058,60.8862,63.5036,69.2804,69.8868
1960,57.7189,78.0204,62.2297,75.1105,81.5076,59.3914,73.9123,75.8740,75.7983,75.4159,...,78.0689,73.2214,66.0903,73.8741,69.2197,63.0560,61.1062,63.7251,70.1158,70.1644
1961,58.0074,78.2347,62.1170,69.3936,81.6309,59.5049,74.1484,76.2682,76.0868,75.5530,...,78.1345,73.3959,66.4161,74.6839,69.1335,63.3635,61.3268,63.8394,70.2208,70.4254
1962,58.2920,78.4212,62.0671,74.6203,81.7016,59.7026,74.3112,76.6421,76.0765,75.6725,...,78.2081,73.5756,66.7549,75.1533,68.9568,63.7366,61.5673,64.1511,70.3304,70.6642
1963,58.5808,78.6150,62.0842,74.5299,81.7717,59.8912,74.4871,77.0067,75.7326,75.7746,...,78.2765,73.7589,67.0820,75.2634,65.3828,64.1477,61.8153,64.5600,70.3938,70.8911
1964,58.8706,78.7762,62.1833,74.6192,81.8219,60.0902,74.6502,77.3599,75.4729,75.8593,...,78.3278,73.9453,67.3783,74.9328,67.2308,64.5807,62.0784,65.7521,70.5657,71.1126
1965,59.1687,78.9203,62.3926,74.8310,81.9382,60.2884,74.9072,77.6921,75.9621,75.9267,...,78.4277,74.1337,67.6945,75.7311,67.3449,65.0163,62.3599,66.1260,70.7371,71.2992
1966,59.4562,79.0666,62.6814,75.1436,82.0627,60.5218,75.1535,78.0012,75.8044,75.9768,...,78.5528,74.3166,68.0355,75.8658,67.9047,65.4493,62.3854,66.8198,71.0043,71.4667
1967,59.7657,79.2167,63.0726,75.4686,82.2618,60.7655,75.3585,78.2898,76.0218,76.0154,...,78.6909,74.4947,68.3298,76.0127,64.6811,65.8949,62.7630,67.1185,71.2742,71.6010
1968,60.0959,79.3639,63.5357,75.7972,82.4508,61.0275,75.5302,78.5616,76.1302,76.0444,...,78.7876,74.6553,68.7249,75.9723,67.9440,66.3628,63.1904,67.3875,71.5907,71.4622
1969,60.4167,79.5032,64.0905,76.0489,82.6505,61.2753,75.7228,78.8288,76.2122,76.0688,...,78.8851,74.8126,69.0915,76.2654,67.1176,66.8546,63.6650,67.6600,71.8590,71.5601
1970,60.7320,79.6464,64.7213,76.2570,82.8388,60.6559,75.9635,79.0734,76.6430,76.0936,...,78.9872,74.9559,69.4511,76.5534,73.2667,67.3539,51.6599,67.9174,72.0749,71.6156
1971,61.0439,79.7978,65.4510,76.3753,83.0965,60.5042,76.1762,79.3198,76.5617,76.1240,...,79.0914,75.0985,69.7826,76.9767,74.8098,67.8604,51.6276,68.1975,72.3504,70.8929
1972,61.3822,79.9665,66.2214,76.5024,83.3399,60.7955,76.3971,79.5791,77.0079,76.1912,...,79.2068,75.2416,70.1645,77.2896,75.1313,68.4073,53.6913,68.5117,72.4846,70.1408
1973,60.0824,80.1270,67.0676,76.5848,83.6280,61.0357,76.6458,79.8407,77.2646,76.2778,...,79.3597,75.3793,70.5946,77.5280,75.5139,68.9617,55.8873,68.8635,72.5354,67.5113
1974,58.5670,80.1989,68.3057,76.7249,83.9141,61.2637,76.8808,80.0816,77.5500,76.3895,...,79.2941,75.5123,71.4276,77.5002,75.8905,69.5168,51.9008,69.2265,72.2184,67.6387
1975,58.7554,80.3305,69.8300,76.9371,84.1908,61.4860,77.0727,80.2768,77.5451,76.5026,...,79.4659,75.6453,71.6259,77.3175,76.1586,70.1195,53.7132,69.6338,71.6302,72.0443
1976,58.6674,80.4414,72.0340,77.1761,84.4119,61.7011,77.2954,80.4384,77.6804,76.6507,...,79.6935,75.7338,72.0310,77.7318,76.5119,70.7383,59.0457,70.0634,71.1238,72.2038
1977,55.0640,80.6061,73.3599,77.3498,84.6092,61.9091,77.5144,80.5892,77.6703,76.8350,...,80.0583,75.8061,72.4007,77.9048,76.8631,71.3553,59.8105,70.1723,70.5326,72.3237
1978,55.3121,80.7740,74.1081,77.4755,84.7583,60.9350,77.7533,80.7071,77.8825,77.0356,...,80.0227,75.9079,72.7175,78.3644,77.1163,72.0318,60.4106,70.7879,69.8618,72.1770
1979,50.0776,80.9350,74.7404,77.5871,84.8713,61.1331,77.9445,80.8010,77.8474,77.2258,...,80.1336,76.0725,72.9488,78.3902,77.4040,72.7812,60.9461,71.2220,69.1284,72.4667
1980,50.5612,81.1171,75.4745,77.7533,84.9494,61.3194,78.1493,80.8467,78.3088,77.3815,...,80.2871,76.3463,73.2086,78.5832,77.5702,73.5928,61.4759,71.5584,68.3054,72.4779
1981,56.5389,81.3592,76.0237,77.8945,85.0363,61.4998,78.4093,80.8575,78.6494,77.4796,...,80.4570,76.6064,73.6805,79.0609,77.8150,74.4143,61.9749,69.3243,67.5154,72.3280
1982,56.7371,81.5326,76.4537,77.9958,85.1072,59.5114,78.6612,80.8378,79.0147,77.4963,...,80.2669,76.8907,73.5682,79.1149,78.1470,75.5067,61.9729,72.1355,66.8561,71.9159
1983,60.7699,81.6171,76.9386,78.0326,85.2629,60.1715,78.9186,80.7824,79.3671,64.5350,...,80.2820,77.0034,74.4727,79.1141,78.6012,76.5185,65.3434,72.3838,66.1476,71.3424
1984,61.7370,81.7096,77.2892,78.0657,85.4352,60.3659,79.2324,80.6396,79.7263,77.3252,...,80.4104,76.9599,74.7176,79.0688,78.6735,77.4326,64.2809,72.6733,65.3387,70.5298
1985,62.0836,81.8232,77.3472,78.2353,85.8022,60.4987,79.4776,80.6070,79.7945,77.1820,...,80.7385,76.7808,75.2345,79.1524,78.7181,78.2114,71.0124,72.9076,64.6240,69.4269
1986,62.2276,81.9880,77.2852,78.4325,86.1526,62.4238,79.7752,80.4983,80.1557,77.0978,...,80.8893,76.4630,75.5763,79.2893,78.8288,78.7490,71.3215,72.9387,63.7719,68.2076
1987,62.7879,82.1766,77.2532,78.6240,86.5596,60.9838,80.0458,80.4377,80.1739,77.0433,...,80.8691,76.1049,75.8265,79.2330,78.9690,79.1912,71.6292,73.1857,63.1449,66.8504
1988,66.9148,82.3991,77.2748,78.6439,86.9168,60.2548,80.3292,80.4664,80.3254,77.1656,...,80.8059,75.7355,76.0593,79.3870,79.1358,78.7273,71.9318,73.3890,62.6789,65.2847
1989,66.3670,82.4982,76.6837,78.6632,87.2884,61.5755,80.5981,80.5932,80.7012,77.3427,...,80.8206,75.4393,76.2433,79.2227,79.3983,79.8913,72.2393,73.3506,62.1111,63.8726
1990,67.4008,82.5789,77.0440,78.6489,87.4940,64.7650,80.8507,80.7196,80.7714,77.5846,...,81.1045,75.3790,76.3104,79.6013,79.7360,80.2983,72.5355,73.9157,61.5796,62.4717
1991,67.8862,82.5682,77.5230,78.6481,87.6851,64.9575,81.1074,80.9712,80.9017,77.8519,...,81.3619,75.4309,76.3364,79.7525,80.0256,80.8211,72.8122,74.0985,61.0194,60.2104
1992,68.1233,81.8671,78.1107,78.6653,87.8113,65.0943,81.3586,81.1831,81.1954,78.1373,...,81.4242,75.6075,76.4318,80.3503,80.2912,81.4226,73.0944,74.3326,60.7557,59.6760
1993,67.1524,82.6107,78.5063,78.5856,87.9391,63.6988,81.5879,81.3461,81.1338,78.4416,...,81.4235,75.6432,76.4607,80.1683,80.7484,82.0143,73.3802,74.5673,60.4172,58.5589
1994,68.9897,82.7233,79.2029,78.5106,88.1927,63.5741,81.8319,81.6063,81.3477,78.7500,...,81.6092,75.6481,76.1328,79.7988,80.9370,82.4360,73.6785,74.8096,60.3527,57.2115
1995,69.2145,82.8799,79.6099,78.4503,88.4875,64.3074,82.0531,81.9329,81.5187,79.0430,...,81.9380,75.6399,76.6169,79.9913,81.0003,82.7584,73.9694,75.0373,60.6887,56.7564
1996,69.5061,83.0341,80.0122,78.5608,88.7695,64.3596,82.2723,82.2053,81.7084,79.3064,...,82.2062,75.8674,76.7361,78.5381,81.1479,82.9779,74.2534,75.2971,61.1556,55.0024
1997,70.0493,83.1472,80.4907,78.7192,89.0421,65.1003,82.5032,82.3127,81.8119,79.5222,...,82.2575,76.2091,76.8180,80.3301,81.2149,83.0407,74.5535,75.5459,61.8160,56.5090
1998,70.6820,83.2965,80.6795,78.7940,89.2989,67.0190,82.7137,82.3649,81.7533,79.6762,...,82.3436,76.4840,76.8914,79.4991,81.2363,83.0705,74.8445,75.8751,62.5637,55.8498
1999,71.0834,83.5871,81.1726,79.1907,89.3928,67.5175,82.9280,82.3575,82.2755,79.7766,...,82.5426,76.6161,76.9232,80.1697,81.0009,83.2205,75.1426,76.0866,63.0567,56.5831
2000,71.2942,83.9607,81.3690,79.2683,89.6477,68.0929,83.1040,82.3683,82.5900,79.8435,...,82.8790,76.6667,77.0697,80.4641,81.0868,83.4040,75.4246,76.3150,63.7237,57.1736
2001,71.3432,84.4256,81.5512,79.2585,89.9195,68.5001,83.3133,82.4894,82.5961,79.8952,...,82.8830,76.8706,76.9919,80.3201,81.1441,83.5594,75.6910,76.5209,64.4740,57.7115
2002,71.4457,85.0258,81.6947,79.2039,90.1611,69.2406,83.4743,82.6846,82.0481,79.9541,...,83.0895,77.2380,76.9667,80.6772,81.2002,83.7599,75.9757,76.7374,65.2034,58.2533
2003,71.9737,85.4890,81.8845,79.2536,90.3699,69.8399,83.6035,83.0241,82.6615,80.0380,...,83.1765,77.5842,77.0802,79.8748,81.2402,83.9172,76.2407,76.9136,66.0705,59.2422
2004,72.3794,85.6568,82.0621,78.0053,90.6014,70.3003,83.7248,83.3187,82.7737,80.1600,...,83.4698,77.8693,77.1524,80.0755,81.2816,83.9800,76.5364,77.0205,66.9250,60.4933
2005,72.6363,85.4733,82.2709,79.3943,90.6948,70.8782,83.8704,83.6197,82.8382,80.3164,...,83.4563,77.9986,77.2523,80.3875,81.3454,83.9968,76.8090,77.1785,67.7658,62.5163
2006,72.9557,85.2839,82.4600,79.4671,90.7930,71.3057,83.9493,83.9275,83.2240,80.4991,...,83.3980,78.1307,77.3648,80.3882,81.4274,84.1064,77.0558,77.2283,68.5876,64.3721
2007,73.2393,84.9973,82.6438,79.5133,90.8288,71.7176,84.0314,83.9890,82.8916,80.6941,...,83.5125,78.2392,77.4932,80.3934,81.4583,84.2151,77.2812,77.2712,69.3387,65.6499
2008,73.5071,84.8549,82.8058,79.5737,90.8997,72.1411,84.2325,83.9225,82.8841,80.9087,...,83.7379,78.3788,77.5436,80.3967,81.5046,84.3181,77.5297,77.5352,69.9732,66.9327
2009,73.4712,84.8480,82.9564,79.4913,90.9760,72.5152,84.2874,83.7689,83.2929,81.1205,...,83.9289,78.5340,77.6044,80.1684,81.5504,84.4370,77.7507,77.4903,70.5278,68.0314
2010,73.3616,85.1499,83.0930,79.4584,91.0214,72.8933,84.3147,83.7350,83.5940,81.3196,...,83.9854,78.7825,77.6935,80.3531,81.6055,84.5851,77.9655,76.2230,71.0807,68.7474
2011,73.5795,85.4168,83.2131,79.4436,90.9820,73.2221,84.4332,83.7978,83.0647,81.5330,...,84.0119,78.9365,77.8728,79.3452,81.6203,84.6689,78.1821,76.4762,71.3815,69.3707
2012,72.8820,85.6616,83.3026,79.6051,90.8597,73.4964,83.9649,83.8558,83.4824,81.7355,...,84.1982,79.0092,77.9498,79.2700,81.6486,84.7431,78.3771,76.3977,71.7318,69.7571
2013,72.7560,85.9935,83.3919,79.5953,90.7478,73.8035,84.7606,83.9345,83.6844,81.9246,...,84.1429,79.1989,78.0505,80.0310,81.7073,84.8658,78.5547,75.1539,72.2365,70.2882
2014,73.1937,86.2291,83.4807,79.5478,90.6112,74.0538,84.9342,83.9545,83.7378,82.0962,...,84.1236,79.2278,78.1810,80.1476,81.7986,85.0726,78.7184,75.7587,72.9361,70.3682
2015,71.5263,84.5616,80.9568,79.4620,85.9325,73.9216,85.1499,83.9408,82.7324,75.6764,...,84.9071,78.5398,77.7492,79.7444,82.9812,85.2281,78.8775,75.4235,73.2892,70.7244
2016,70.3183,83.5718,82.9103,79.4927,88.8391,73.5724,84.8946,83.9490,80.7574,79.3409,...,81.9701,78.7135,77.2663,78.8997,81.6958,84.4948,79.0780,74.9329,72.1100,69.1576
2017,75.6159,85.5569,83.8087,79.5302,90.5326,74.7739,85.5844,84.2200,82.6124,81.4055,...,83.0513,79.1283,78.6081,79.9506,82.0417,85.5343,79.2651,76.8438,75.0166,71.4307
2018,75.9220,86.3595,83.9010,79.6241,90.5553,75.0080,85.7620,84.3227,84.1949,82.4296,...,84.6663,79.3779,78.7511,79.8957,82.1112,85.6520,79.4421,78.1426,75.9474,71.7437
2019,75.9220,86.3595,83.9010,79.6241,90.5553,75.0080,85.7620,84.3227,84.1949,82.4296,...,84.6663,79.3779,78.7511,79.8957,82.1112,85.6520,79.4421,78.1426,75.9474,71.7437
2020,75.9220,86.3595,83.9010,79.6241,90.5553,75.0080,85.7620,84.3227,84.1949,82.4296,...,84.6663,79.3779,78.7511,79.8957,82.1112,85.6520,79.4421,78.1426,75.9474,71.7437

In [5]:
da_countrymasks

<xarray.DataArray (lat: 391, lon: 499, country: 49)>
dask.array<getitem, shape=(391, 499, 49), dtype=float32, chunksize=(337, 430, 18), chunktype=numpy.ndarray>
Coordinates:
  * lon      (lon) float64 -14.95 -14.85 -14.75 -14.65 ... 34.65 34.75 34.85
  * lat      (lat) float64 32.05 32.15 32.25 32.35 ... 70.75 70.85 70.95 71.05
  * country  (country) object 'ALB' 'AND' 'AUT' 'BEL' ... 'TUN' 'TUR' 'UKR'

In [ ]:
da_countrymasks.country


# TODO: try to plot this - match ISO3 to numeric ISO3

<xarray.DataArray 'country' (country: 49)>
array(['ALB', 'AND', 'AUT', 'BEL', 'BGR', 'BIH', 'BLR', 'CHE', 'CYP', 'CZE',
       'DEU', 'DNK', 'DZA', 'ESP', 'EST', 'FIN', 'FRA', 'FRO', 'GBR', 'GRC',
       'HRV', 'HUN', 'IMN', 'IRL', 'ISL', 'ISR', 'ITA', 'LBY', 'LTU', 'LUX',
       'LVA', 'MAR', 'MDA', 'MKD', 'MLT', 'MNE', 'NLD', 'NOR', 'POL', 'PRT',
       'ROU', 'RUS', 'SRB', 'SVK', 'SVN', 'SWE', 'TUN', 'TUR', 'UKR'],
      dtype=object)
Coordinates:
  * country  (country) object 'ALB' 'AND' 'AUT' 'BEL' ... 'TUN' 'TUR' 'UKR'

In [ ]:
df_lookuptable

,SSP name,ISO name,WPP name,ISO alpha-2,ISO alpha-3,ISO numeric,Data availability,Suggested gapfill
0,Afghanistan,Afghanistan,Afghanistan,AF,AFG,4,Full historical + SSP,NaN
1,Albania,Albania,Albania,AL,ALB,8,Full historical + SSP,NaN
2,Algeria,Algeria,Algeria,DZ,DZA,12,Full historical + SSP,NaN
3,Angola,Angola,Angola,AO,AGO,24,Full historical + SSP,NaN
4,Antigua and Barbuda,Antigua and Barbuda,Antigua and Barbuda,AG,ATG,28,Full historical + SSP,NaN
...,...,...,...,...,...,...,...,...
244,NaN,Norfolk Island,NaN,NF,NFK,574,No data,Rest of Asia (R10)
245,NaN,Pitcairn,NaN,PN,PCN,612,No data,Rest of Asia (R10)
246,NaN,South Georgia and the South Sandwich Islands,NaN,GS,SGS,239,No population,NaN
247,NaN,Svalbard and Jan Mayen,NaN,SJ,SJM,744,No data,Europe (R10)
248,NaN,United States Minor Outlying Islands,NaN,UM,UMI,581,No population,NaN

In [ ]:
df_lookuptable[df_lookuptable['ISO alpha-3'].isin(da_countrymasks.country.values)].reset_index(drop=True)


# all the countries included in bounding box - decide whether to get rid of some!

,SSP name,ISO name,WPP name,ISO alpha-2,ISO alpha-3,ISO numeric,Data availability,Suggested gapfill
0,Albania,Albania,Albania,AL,ALB,8,Full historical + SSP,NaN
1,Algeria,Algeria,Algeria,DZ,DZA,12,Full historical + SSP,NaN
2,Austria,Austria,Austria,AT,AUT,40,Full historical + SSP,NaN
3,Belarus,Belarus,Belarus,BY,BLR,112,Full historical + SSP,NaN
4,Belgium,Belgium,Belgium,BE,BEL,56,Full historical + SSP,NaN
5,Bosnia and Herzegovina,Bosnia and Herzegovina,Bosnia and Herzegovina,BA,BIH,70,Full historical + SSP,NaN
6,Bulgaria,Bulgaria,Bulgaria,BG,BGR,100,Full historical + SSP,NaN
7,Croatia,Croatia,Croatia,HR,HRV,191,Full historical + SSP,NaN
8,Cyprus,Cyprus,Cyprus,CY,CYP,196,Full historical + SSP,NaN
9,Czechia,Czechia,Czechia,CZ,CZE,203,Full historical + SSP,NaN
10,Denmark,Denmark,Denmark,DK,DNK,208,Full historical + SSP,NaN
11,Estonia,Estonia,Estonia,EE,EST,233,Full historical + SSP,NaN
12,Finland,Finland,Finland,FI,FIN,246,Full historical + SSP,NaN
13,France,France,France,FR,FRA,250,Full historical + SSP,NaN
14,Germany,Germany,Germany,DE,DEU,276,Full historical + SSP,NaN
15,Greece,Greece,Greece,GR,GRC,300,Full historical + SSP,NaN
16,Hungary,Hungary,Hungary,HU,HUN,348,Full historical + SSP,NaN
17,Iceland,Iceland,Iceland,IS,ISL,352,Full historical + SSP,NaN
18,Ireland,Ireland,Ireland,IE,IRL,372,Full historical + SSP,NaN
19,Israel,Israel,Israel,IL,ISR,376,Full historical + SSP,NaN
20,Italy,Italy,Italy,IT,ITA,380,Full historical + SSP,NaN
21,Latvia,Latvia,Latvia,LV,LVA,428,Full historical + SSP,NaN
22,Libya,Libya,Libya,LY,LBY,434,Full historical + SSP,NaN
23,Lithuania,Lithuania,Lithuania,LT,LTU,440,Full historical + SSP,NaN
24,Luxembourg,Luxembourg,Luxembourg,LU,LUX,442,Full historical + SSP,NaN
25,Malta,Malta,Malta,MT,MLT,470,Full historical + SSP,NaN
26,Moldova,Moldova (Republic of),Republic of Moldova,MD,MDA,498,Full historical + SSP,NaN
27,Montenegro,Montenegro,Montenegro,ME,MNE,499,Full historical + SSP,NaN
28,Morocco,Morocco,Morocco,MA,MAR,504,Full historical + SSP,NaN
29,Netherlands,Netherlands,Netherlands,NL,NLD,528,Full historical + SSP,NaN
30,North Macedonia,North Macedonia,North Macedonia,MK,MKD,807,Full historical + SSP,NaN
31,Norway,Norway,Norway,NO,NOR,578,Full historical + SSP,NaN
32,Poland,Poland,Poland,PL,POL,616,Full historical + SSP,NaN
33,Portugal,Portugal,Portugal,PT,PRT,620,Full historical + SSP,NaN
34,Romania,Romania,Romania,RO,ROU,642,Full historical + SSP,NaN
35,Russian Federation,Russian Federation,Russian Federation,RU,RUS,643,Full historical + SSP,NaN
36,Serbia,Serbia,Serbia,RS,SRB,688,Full historical + SSP,NaN
37,Slovakia,Slovakia,Slovakia,SK,SVK,703,Full historical + SSP,NaN
38,Slovenia,Slovenia,Slovenia,SI,SVN,705,Full historical + SSP,NaN
39,Spain,Spain,Spain,ES,ESP,724,Full historical + SSP,NaN
40,Sweden,Sweden,Sweden,SE,SWE,752,Full historical + SSP,NaN
41,Switzerland,Switzerland,Switzerland,CH,CHE,756,Full historical + SSP,NaN
42,Tunisia,Tunisia,Tunisia,TN,TUN,788,Full historical + SSP,NaN
43,Turkey,Turkey,Türkiye,TR,TUR,792,Full historical + SSP,NaN
44,Ukraine,Ukraine,Ukraine,UA,UKR,804,Full historical + SSP,NaN
45,United Kingdom,United Kingdom of Great Britain and Northern I...,United Kingdom,GB,GBR,826,Full historical + SSP,NaN
46,Andorra,Andorra,Andorra,AD,AND,20,Only historical until 2015,Europe (R10)
47,Faroe Islands,Faroe Islands,Faroe Islands,FO,FRO,234,Only historical until 2015,Europe (R10)
48,Isle of Man,Isle of Man,Isle of Man,IM,IMN,833,Only historical until 2015,Europe (R10)

## Part 2. Lifetime exposure

In [ ]:
# GMT-mapping + lifetime exposure functions

# TODO